In [15]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error
# import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("job_salary_prediction_dataset.csv")
df.shape

(250000, 10)

In [3]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [4]:
print("************************************")
print(df["job_title"].value_counts())
print("************************************")
print("************************************")
print(df["education_level"].value_counts())
print("************************************")
print("************************************")
print(df["industry"].value_counts())
print("************************************")
print("************************************")
print(df["company_size"].value_counts())
print("************************************")
print("************************************")
print(df["location"].value_counts())
print("************************************")
print("************************************")
print(df["remote_work"].value_counts())
print("************************************")

************************************
job_title
Backend Developer            21125
Cybersecurity Analyst        20959
Product Manager              20950
AI Engineer                  20945
Data Scientist               20890
DevOps Engineer              20889
Software Engineer            20876
Data Analyst                 20722
Cloud Engineer               20686
Machine Learning Engineer    20677
Business Analyst             20648
Frontend Developer           20633
Name: count, dtype: int64
************************************
************************************
education_level
Master         50352
High School    50065
Bachelor       49950
PhD            49857
Diploma        49776
Name: count, dtype: int64
************************************
************************************
industry
Finance          25393
Consulting       25258
Media            25034
Manufacturing    25024
Technology       24903
Government       24901
Healthcare       24898
Education        24889
Telecom          24859
Retail           24841
Name: count, dtype: int64
************************************
************************************
company_size
Large         50254
Small         50235
Medium        50027
Enterprise    49875
Startup       49609
Name: count, dtype: int64
************************************
************************************
location
Australia      25258
Canada         25165
Sweden         25100
Remote         25065
Singapore      25035
USA            24931
UK             24927
India          24895
Netherlands    24861
Germany        24763
Name: count, dtype: int64
************************************
************************************
remote_work
No        83621
Hybrid    83476
Yes       82903
Name: count, dtype: int64
************************************

In [5]:
dummy =pd.get_dummies(
    df[["job_title","education_level", "industry","company_size","location","remote_work"]], 
    drop_first=True, 
    dtype=int
)
dummy.head()

,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,job_title_Frontend Developer,job_title_Machine Learning Engineer,job_title_Product Manager,...,location_Germany,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_No,remote_work_Yes
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1

In [6]:
ndf = pd.concat([df,dummy], axis='columns')
ndf.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,...,location_Germany,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_No,remote_work_Yes
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,...,0,1,0,0,0,0,0,0,0,0
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,...,0,0,0,0,0,0,0,0,1,0
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,...,0,0,0,0,1,0,0,0,1,0
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,...,0,0,0,0,0,0,0,0,0,1
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,...,0,0,0,0,0,1,0,0,0,1

In [7]:
ndf=ndf.drop(["job_title","education_level", "industry","company_size","location","remote_work"], axis='columns')
ndf.head()

,experience_years,skills_count,certifications,salary,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,...,location_Germany,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_No,remote_work_Yes
0,10,2,2,109413,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,5,17,0,93764,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
2,18,4,1,148123,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3,19,13,0,189123,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,15,7,0,165069,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1

In [8]:
X= ndf.drop("salary", axis = 'columns')
X.head()

,experience_years,skills_count,certifications,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,...,location_Germany,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_No,remote_work_Yes
0,10,2,2,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,5,17,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
2,18,4,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3,19,13,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,15,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1

In [9]:
y = ndf.salary
y.head()

0    109413
1     93764
2    148123
3    189123
4    165069
Name: salary, dtype: int64

In [10]:

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [11]:
model.score(X_test,y_test)

0.963672431132662

In [12]:
y_predicted=model.predict(X_test)
y_predicted

array([222335.02925287, 168772.0998078 ,  89439.39863731, ...,
       176567.02588651, 174065.23658432, 180759.42008761])

In [13]:
r2 = r2_score(y_test, y_predicted)
r2

0.963672431132662

In [14]:
mse = mean_squared_error(y_test, y_predicted)
mse

51067174.4345229

In [29]:
poly = PolynomialFeatures(degree=2, interaction_only=True)
X_test_poly = poly.fit_transform(X_test)
X_train_poly = poly.fit_transform(X_train)

In [30]:
model = LinearRegression()
model.fit(X_train_poly,y_train)

LinearRegression()

In [31]:
model.score(X_test_poly,y_test)

0.9820393452704532

In [32]:
y_predicted=model.predict(X_test_poly)
r2 = r2_score(y_test, y_predicted)
r2

0.9820393452704532

In [33]:
mse = mean_squared_error(y_test, y_predicted)
(mse**(.5)/250000)*100

2.009897085681098

In [36]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge

In [39]:
model = Pipeline([
    ("poly", PolynomialFeatures(degree=2)),
    ("ridge", Ridge(alpha=1.0))
])

# Train
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse_percent = (rmse / y_test.mean()) * 100
score = model.score(X_test, y_test)
r2 = r2_score(y_test, y_pred)

print("RMSE:", rmse_percent)
print("Score:", score)
print("R2:", r2)

RMSE: 3.451472965951157
Score: 0.9820410948216808
R2: 0.9820410948216808